Update YAML.

diff --git a/.github/workflows/verify.yaml b/.github/workflows/verify.yaml
--- a/.github/workflows/verify.yaml
+++ b/.github/workflows/verify.yaml
@@ -47,11 +47,19 @@ jobs:
             echo "Default Test failed. Expected 'Hello.', got '$response_default'"
             exit 1
           fi
-
+          
 
           if [ "$response_fib" == "[0,1,1,2,3,5,8,13,21,34,55,89,144,233,377,610,987,1597]" ]; then
             echo "Fibonacci test passed!"
           else
             echo "Fibonacci test failed. Expected '[0,1,1,2,3,5,8,13,21,34,55,89,144,233,377,610,987,1597]', got '$response_fib'"
+            exit 1
+          fi
+          
+          if [ "$response_total" == "You have $0.0 in the Piggy Bank." ]; then
+            echo "Total money test passed!"
+          else
+            echo "Total money test failed. Expected 'You have $0.0 in the Piggy Bank.', got '$response_fib'"
+            echo "$response_total"
             exit 1
           fi
